version: '3'
services:
  app:
    container_name: "node_app"
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "2000:2000"
    depends_on:
      - db
    volumes:
      - ./backend/app.js:/app/app.js
      - ./backend/message.html:/app/message.html
  chatbot:
    container_name: "chatbot"
    build:
      context: chatbot
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./chatbot/assets:/app/assets
      - ./chatbot/components:/app/components
      - ./chatbot/pages:/app/pages
      - ./chatbot/nuxt.config.ts:/app/nuxt.config.ts
  db:
    container_name: "db"
    image: mongo:5.0.22
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
